### PR TITLE
Fix template search

### LINKED ISSUE #520: [BUG] DeployVM Wizard does not properly search for templates
**Describe the bug**
In the deploy VM wizard, the search only searches the current selection of templates and does not query the backend

**To Reproduce**

1. Log in as a User or an Admin
2. Go to Create new VM
3. Search for a template

**Expected behavior**
An api call with the keyword should be called

### PR DESCRIPTION
**Pull request by davidjumani**
Fixes #520

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@rhtyd @ravening Please reveiw

File: src/views/compute/wizard/TemplateIsoSelection.vue [hunk 1]
```diff
@@ -232,6 +236,60 @@ export default {
...
+      this.isLoading = true
+      // Fetch templates/isos for all filters
+      templateFilter.forEach(filter => {
+        params.templatefilter = filter
+        promises.push(this.fetchTemplatesIsos(apiCommand, keyword, params))
+      })
+
+      Promise.all(promises).then(response => {
+        response.forEach((resItem) => {
+          const concatTemplates = _.concat(templates, _.get(resItem, apiCommandResponse, []))
```
Comment (davidjumani) [inline src/views/compute/wizard/TemplateIsoSelection.vue:274]: @rhtyd @ravening Keeping it this way to not introduce too many changes, but since we're getting the API response per filter, we can set the datasource here itself. Would also need changes in DeployVM

Comment (davidjumani) [reply src/views/compute/wizard/TemplateIsoSelection.vue:274]: Also zoneid doesn't get passed, need to address that too but preferably in another PR where we move the search functionality to DeployVM like other view do

Comment (ravening) [reply src/views/compute/wizard/TemplateIsoSelection.vue:274]: yeah zoneid is sometimes a crucial parameter. code LGTM apart from the above mentioned missing stuffs

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@rhtyd @ravening Please review. Moved the search to DeployVM itself to simplify things and for consistancy

**Comment by ravening** [comment]
@davidjumani I can no longer see "Centos template" while deploying vm while in old ui, I can still see it

```
"isdynamicallyscalable": false,
      "isextractable": true,
      "isfeatured": true,
      "ispublic": true,
      "isready": true,
      "name": "CentOS 5.5(64-bit) no GUI (KVM)",
      "ostypeid": "90004bff-c29e-11ea-a58c-06c95c00338b",
      "ostypename": "CentOS 5.5 (64-bit)",
```

Old ui

Screenshot 2020-07-22 at 08 57 19


New ui

Screenshot 2020-07-22 at 08 57 39

**Comment by davidjumani** [comment]
@ravening That's proabably because it's not available in the selected zone. Could you check it via cmk by passing the zoneid ?

**Comment by ravening** [comment]
@davidjumani yes it belongs to the same zone

```
(local) mgt01 > list templates templatefilter=featured filter=name zoneid=576f-d7d-44d-8eeb-be71712
{
  "count": 3,
  "template": [
    {
      "name": "Ubuntu 16.04 x64 5G 20200617T1316"
    },
    {
      "name": "ubuntu1"
    },
    {
      "name": "CentOS 5.5(64-bit) no GUI (KVM)"
    }
  ]
}
```

**Comment by davidjumani** [comment]
@ravening Could you check the api call being made? 
This is what I'm getting
```
page=1
pageSize=10
zoneid=04ccc336-d730-42fe-8ff6-5ae36e141e81
templatefilter=featured
command=listTemplates
response=json
```
And able to see the default CentOS template

**Comment by ravening** [comment]
> @ravening Could you check the api call being made?
> This is what I'm getting
> 
> ```
> page=1
> pageSize=10
> zoneid=04ccc336-d730-42fe-8ff6-5ae36e141e81
> templatefilter=featured
> command=listTemplates
> response=json
> ```
> 
> And able to see the default CentOS template

Yes i can see those parameters but cant see the centos template in ui

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

> Yes i can see those parameters but cant see the centos template in ui

@ravening Is the api query returning the right response? Since no keyword is being passed to it. Or perhaps you're within a project

**Comment by ravening** [comment]
> > Yes i can see those parameters but cant see the centos template in ui
> 
> @ravening Is the api query returning the right response? Since no keyword is being passed to it. Or perhaps you're within a project

I was logged in as root admin but if you are seeing centos then its fine
