### PR TITLE
network: fix create offering values

### LINKED ISSUE #757: [BUG] Network Offering form security options are not saved correctly
**Describe the bug**
When creating a network offering with "promiscuous mode", "forged transmits" and "MAC address changes" on Primate it sets the values on the "network_offering_details" table as "accept" when the correct value that should be set is "true".

**To Reproduce**

1. Log in as an Admin
2. Go to 'network offerings'
3. Create a network offering with the 3 security settings enabled
4. On the "network_offering_details" they will have the value "accept".

**Expected behavior**
Value for security settings should be "true"

**Screenshots**

Promisc

### PR DESCRIPTION
**Pull request by shwstppr**
Fixes #757 

createNetworkOffering API should have values for keys - `promiscuousmode`, `macaddresschanges`, `forgedtransmits` of `details` param as `true` or `false`

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

@rhtyd @davidjumani please check cc @alexandremattioli

File: src/views/offering/AddNetworkOffering.vue [hunk 1]
```diff
@@ -894,13 +894,13 @@ export default {
         if ('egressdefaultpolicy' in values && values.egressdefaultpolicy !== 'allow') {
           params.egressdefaultpolicy = false
         }
-        if ('promiscuousmode' in values) {
+        if ('promiscuousmode' in values && values.promiscuousmode !== '') {
```
Comment (davidjumani) [inline src/views/offering/AddNetworkOffering.vue:897]: @shwstppr Would this be simpler ?
```
if (values.promiscuousmode)
```

**Review by davidjumani — APPROVED** [review]
LGTM. Added a minor comment. Thanks @shwstppr

**Review by GabrielBrascher — APPROVED** [review]
