### PR TITLE
storage: fix volume actions

### LINKED ISSUE #225: [BUG] Storage > Volumes > selected volume showing more actions than old UI
**Describe the bug**
The Primate UI has more actions in 'Storage > Volumes > selected volume' than the old UI. Here are the actions that are present only in Primate:
- Detach volume
- Migrate volume
- Download volume
- Create template from volume
- Delete volume

**To Reproduce**
1. Go to 'Storage > Volumes' and click on a volume. Look at the possible actions.

**Expected behavior**
The Primate UI should have the same actions as in the old UI.

**Screenshots**
Old UI:
image

New UI:
image

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

### PR DESCRIPTION
**Pull request by shwstppr**
Fixes #225

### CODE REVIEW

File: src/config/section/storage.js [hunk 1]
```diff
@@ -163,7 +163,12 @@ export default {
           icon: 'delete',
           label: 'Delete Volume',
           dataView: true,
-          groupAction: true
+          groupAction: true,
+          show: (record, store) => { // g_allowUserExpungeRecoverVolume
```
Comment (rhtyd) [inline src/config/section/storage.js]: @shwstppr can you explain the comment, do we need to check anything else? Shouldn't we allow users to delete a volume?

Comment (shwstppr) [reply src/config/section/storage.js]: @rhtyd just checked g_allowUserExpungeRecoverVolume is value from capabilities, `json.listcapabilitiesresponse.capability.allowuserexpungerecovervolume`. How to access that in Primate if set globally?

For users, role based check is an OR condition so it will show up for user
Screenshot from 2020-03-27 17-02-56

**Comment by shwstppr** [comment]
@rhtyd you can review this

File: src/config/section/storage.js [hunk 2]
```diff
@@ -150,20 +150,45 @@ export default {
...
         {
           api: 'deleteVolume',
           icon: 'delete',
           label: 'Delete Volume',
           dataView: true,
-          groupAction: true
+          groupAction: true,
+          show: (record, store) => {
+            return ['Expunging', 'Expunged', 'UploadError'].includes(record.state) ||
+              ((['Admin', 'DomainAdmin'].includes(store.userInfo.roletype) || store.getters.features.allowuserexpungerecovervolume) && record.state === 'Destroy')
```
Comment (rhtyd) [inline src/config/section/storage.js:178]: @shwstppr  are users not allowed to delete volumes?

Comment (shwstppr) [reply src/config/section/storage.js:178]: @rhtyd User account can delete volume if `allowuserexpungerecovervolume` is returned true by capabilities API

https://github.com/apache/cloudstack/blob/master/ui/scripts/storage.js#L3107-L3122

File: src/config/section/storage.js [hunk 3]
```diff
@@ -150,20 +150,45 @@ export default {
...
+          }
+        },
+        {
+          api: 'destroyVolume',
+          icon: 'delete',
+          label: 'Destroy Volume',
+          dataView: true,
+          args: (record, store) => {
```
Comment (rhtyd) [inline src/config/section/storage.js:186]: @shwstppr args is expected to be an array not a function; this would require some changes in AutogenView. On testing I'm getting:
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in v-on handler: "TypeError: action.args.map is not a function"

found in

---> <ActionButton> at src/components/view/ActionButton.vue
       <ACol>
         <ARow>
           <ACard>
             <Resource> at src/views/AutogenView.vue
               <RouteView> at src/layouts/RouteView.vue... (1 recursive calls)
                 <Anonymous>
                   <ALayoutContent>
                     <Anonymous>
                       <ALayout>
                         <Anonymous>
                           <ALayout>
                             <GlobalLayout> at src/components/page/GlobalLayout.vue
                               <BasicLayout> at src/layouts/BasicLayout.vue
                                 <ALocaleProvider>
                                   <App> at src/App.vue
                                     <Root>
```

**Comment by rhtyd** [comment]
@shwstppr please review existing actions against old UI implementation; it seems some cases are not covered. There is another issue with the `args`. Have you tested your changes?

**Comment by shwstppr** [comment]
@rhtyd fixed actions and args error. Tested for different scenarios

Allocated volume without VM
Screenshot from 2020-04-23 11-07-54
ROOT disk for stopped VM
Screenshot from 2020-04-23 11-08-33
DATA disk for stopped VM
Screenshot from 2020-04-23 11-21-52
ROOT disk for running VM
Screenshot from 2020-04-23 11-09-48
DATA disk for running VM
Screenshot from 2020-04-23 11-09-25
Ready volume without VM
Screenshot from 2020-04-23 11-20-49

**Comment by rhtyd** [comment]
- There were discrepancies when data disk was in destroy state (but not expunged)
- the args() method is passed store.getters, but still store.getters.features... was called leading to exception
- no explicit check if args was a method, could lead to exception if args was not an array
