### PR TITLE
view: router resolution based routing for entities in info

### LINKED ISSUE #233: [BUG] Domain admin: non-working links (insufficient rights)
**Describe the bug**
The following links could generate (if the domain admin lacks the required permissions) a 404 (not found) or 500 (Internal server error) errors - template, zone, host, cluster, pod, domain, account, compute offering, storage pool.

**To Reproduce**
1. Log in as domain admin, go to 'Network > Guest networks' and click on a network. Then try the 'Zone' and 'Domain' links - first returns '404' (Not found) error and the second - '500' (Internal server error).

**Expected behavior**
All links should work or be hidden (if the permissions are insufficient).

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
Affected areas:
> Instances > selected instance - 
- template - 404
- host - 404
- zone - 404

> Volumes - selected
- compute offering - 404
- storage pool - 404
- cluster - 404
- pod - 404
- zone - 404

> Snapshots - selected
- zone - 404

> VM Snapshots - selected
- zone - 404

> Guest networks
- zone - 404
- domain - 500

> Images > Templates - selected
- Zone 404
- account - 500
- domain - 500

> Images > ISOs - selected
- account - 500
- domain - 500

> Offerings > System Offerings - 404

### LINKED ISSUE #245: [BUG] Normal user: non-working links (insufficient rights)
**Describe the bug**
The following links could generate (if the normal user lacks the required permissions) a 404 (not found) or 500 (Internal server error) errors - template, zone, host, domain, account, compute offering.

**To Reproduce**
1. Log in as normal user, go to 'Network > Guest networks' and click on a network. Then try the 'Zone' and 'Domain' links - they returns '404' (Not found) error.

**Expected behavior**
All links should work or be hidden (if the permissions are insufficient).

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
Affected areas:
> Instances
- compute offering - 404
- template - 404
- host - 404
- zone - 404
- domain - 404

> Instance groups
- domain - 404

> SSH Key Pairs
- domain - 404

> Affinity groups
- domain - 404

> Storage > Volumes
- compute offering - 404
- zone - 404
- domain - 404

> Storage > Snapshots
- zone - 404
- domain - 404

> Storage > VM Snapshots
- zone - 404
- domain - 404

> Network - Guest networks
- zone - 404
- domain - 404

> Network - VPC
- zone - 404
- domain - 404

> Network - Security groups
- domain - 404

> Network - Public IP Addresses
- zone - 404
- domain - 404

> Network - VPN Users
- domain - 404

> Images > Templates - selected
- Zone - 404
- account - 500
- domain - 404

> Images > ISOs - selected
- Zone 404
- account - 500
- domain - 404

> Projects
- domain - 404

> Identify and access
- domain - 404

> Quota
- domain - 404

### PR DESCRIPTION
**Pull request by shwstppr**
Fixes #245
Fixes #233 

In info card, routing should be done based on user role. User accounts should not be routed to the domain, zone info. And domain admin accounts should not be routed to zone info.

Screenshot from 2020-03-31 16-17-09

### CODE REVIEW

File: src/components/view/InfoCard.vue [hunk 1]
```diff
@@ -419,7 +419,7 @@
           <div class="resource-detail-item__label">{{ $t('zone') }}</div>
           <div class="resource-detail-item__details">
             <a-icon type="global" />
-            <router-link v-if="!resource.zoneid.includes(',')" :to="{ path: '/zone/' + resource.zoneid }">{{ resource.zonename || resource.zoneid }}</router-link>
+            <router-link v-if="!resource.zoneid.includes(',') && this.isAdmin()" :to="{ path: '/zone/' + resource.zoneid }">{{ resource.zonename || resource.zoneid }}</router-link>
```
Comment (rhtyd) [inline src/components/view/InfoCard.vue:422]: @shwstppr instead of such role specific checks, we should check if the vue route is routable at all or not?

Comment (shwstppr) [reply src/components/view/InfoCard.vue:422]: @rhtyd how to check that?
Like for zone, we have a link like `http://localhost:5050/#/zone/00bef679-f1b8-4cfa-95de-c1e9ee098823`. Can we somehow ascertain this will return 404 because zone does actually exist and only logged-in account doesn't have the privilege to see info

Comment (rhtyd) [reply src/components/view/InfoCard.vue:422]: @shwstppr search and see examples on using $router.resolve to check if the link is routable; something similar perhaps?
